#!/usr/bin/env python3
import argparse
import asyncio
import json
import logging
import re
import time
from pathlib import Path

import yaml
import uvicorn
import zenoh

from state import SharedState
from vehicle_bridge import VehicleProtocol, _DISCONNECT_TIMEOUT
from station_bridge import StationBridge
from web.server import create_app
from web.video_relay import video_relay

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s  %(levelname)-7s  %(name)s: %(message)s',
    datefmt='%H:%M:%S',
)
logger = logging.getLogger('main')


def load_config(path: str, overrides: dict) -> dict:
    cfg = {}
    p = Path(path)
    if p.exists():
        cfg = yaml.safe_load(p.read_text()) or {}
    cfg.update({k: v for k, v in overrides.items() if v is not None})
    return cfg


def sync_zenohd_config(locator: str, zenohd_path: str = 'zenohd.json5') -> None:
    m = re.search(r':(\d+)$', locator)
    if not m:
        logger.warning(f'Failed to parse zenoh_locator port: {locator!r} — zenohd.json5 not updated')
        return
    port = m.group(1)
    Path(zenohd_path).write_text(
        '{\n'
        '  // This file is auto-generated by main.py using config.yaml zenoh_locator port.\n'
        '  // Do not edit this file directly; change only the port in config.yaml.\n'
        '  //\n'
        '  // Run: zenohd --config zenohd.json5\n'
        '\n'
        '  listen: {\n'
        f'    endpoints: ["tcp/0.0.0.0:{port}"],\n'
        '  },\n'
        '\n'
        '  scouting: {\n'
        '    multicast: {\n'
        '      // Disable multicast in WAN environments\n'
        '      enabled: false,\n'
        '    },\n'
        '  },\n'
        '}\n'
    )
    logger.info(f'zenohd.json5 → port {port}')


async def run_send_loop(state: SharedState, proto: VehicleProtocol, cfg: dict):
    hb_interval        = 1.0 / cfg.get('heartbeat_rate',   5.0)
    push_interval      = cfg.get('state_push_interval', 0.05)  # 20 Hz
    station_timeout    = cfg.get('station_timeout', 2.0)
    disconnect_timeout = _DISCONNECT_TIMEOUT

    last_hb   = 0.0
    last_push = 0.0
    _veh_disconnected = False

    while True:
        now = time.monotonic()

        if state.last_vehicle_recv > 0:
            age = now - state.last_vehicle_recv
            if age > disconnect_timeout and not _veh_disconnected:
                _veh_disconnected = True
                logger.warning('Vehicle disconnected')
            elif age < 1.0 and _veh_disconnected:
                _veh_disconnected = False
                logger.info('Vehicle reconnected')

        if state.station_connected and state.station_last_recv > 0:
            if now - state.station_last_recv > station_timeout:
                logger.warning('Station heartbeat timeout — marking disconnected')
                state.update_station_connected(False)

        proto.calc_bandwidth()

        if now - last_hb >= hb_interval:
            proto.send_heartbeat()
            last_hb = now

        if now - last_push >= push_interval:
            state._validate()
            state._broadcast_sync()
            last_push = now

        await asyncio.sleep(0.01)


async def run(cfg: dict):
    web_port = cfg.get('web_port', 8080)
    locator  = cfg.get('zenoh_locator', '')

    if locator:
        sync_zenohd_config(locator)

    state = SharedState()
    loop  = asyncio.get_running_loop()

    video_relay.init(
        loop,
        on_decode_ms=lambda ms: setattr(state.network, 'decode_delay', ms),
    )

    zconf = zenoh.Config()
    if locator:
        zconf.insert_json5('connect/endpoints', json.dumps([locator]))
    session = zenoh.open(zconf)
    logger.info(f'Zenoh session opened → {locator or "auto-discovery"}')

    vehicle_proto = VehicleProtocol(state, loop)
    vehicle_proto.start(session)

    station_bridge = StationBridge(state, loop, vehicle_proto, cfg)
    station_bridge.start(session)

    app = create_app(state, vehicle_proto)
    uv_cfg = uvicorn.Config(
        app,
        host='0.0.0.0',
        port=web_port,
        log_level='warning',
        loop='none',
    )
    server = uvicorn.Server(uv_cfg)
    logger.info(f'Web  http://0.0.0.0:{web_port}')

    try:
        await asyncio.gather(
            run_send_loop(state, vehicle_proto, cfg),
            server.serve(),
        )
    finally:
        await video_relay.cleanup()
        station_bridge.stop()
        vehicle_proto.stop()
        session.close()
        logger.info('Shutdown complete')


def main():
    parser = argparse.ArgumentParser(description='NEV Teleop Server')
    parser.add_argument('--config',       default='config.yaml')
    parser.add_argument('--zenoh-locator', default=None)
    parser.add_argument('--web-port',      type=int, default=None)
    args = parser.parse_args()

    cfg = load_config(args.config, {
        'zenoh_locator': args.zenoh_locator,
        'web_port':      args.web_port,
    })

    try:
        asyncio.run(run(cfg))
    except KeyboardInterrupt:
        logger.info('Stopped by user')


if __name__ == '__main__':
    main()
